### PR TITLE
Content amends to keeping-schools-open-for-children-of-key-workers

### PR DESCRIPTION
**Pull request by benilovj**

### CODE REVIEW

**Comment by benilovj** [comment]
@emmajhf the previews should work now, you can click on "View deployment" on the pull request page to navigate to the preview app.

**Comment by emmajhf** [comment]
@benilovj I spotted something that needs to come out. Sorry, I didn't highlight the deletion on the googledoc. It's the section 'If you’re a key worker and you’re able to work from home' (sub-head and text below it). We can cut this because the scenario is covered by the new 'When to keep your children at home' section.

Also, what do you think about the spacing overall? There seems to be a lot of white space, but I wonder if the alternative is something a bit squished.

**Comment by emmajhf** [comment]
@benilovj I spotted something that needs to come out. Sorry, I didn't highlight the deletion on the googledoc. It's the section 'If you’re a key worker and you’re able to work from home' (sub-head and text below it). We can cut this because the scenario is covered by the new 'When to keep your children at home' section.

Also, what do you think about the spacing overall? There seems to be a lot of white space, but I wonder if the alternative is something a bit squished.

**Comment by benilovj** [comment]
> @benilovj I spotted something that needs to come out. Sorry, I didn't highlight the deletion on the googledoc. It's the section 'If you’re a key worker and you’re able to work from home' (sub-head and text below it). We can cut this because the scenario is covered by the new 'When to keep your children at home' section.

Done.

I'll take a look at the spacing separately...

**Pull request merged**
